### ISSUE TITLE
Screenshot parameters? 

### ISSUE THREAD

**Issue by echadwick-artist** [DRx3D/glTF-Sample-Assets-OLD#8]
What image format and what resolutions are recommended for screenshots?

This is not outlined in the readme: https://github.com/DrX3D/glTF-Sample-Assets/blob/main/SubmittingModels.md 

However in the past I've been advised by replies in my pull requests to use specific file naming (screenshot.jpg, screenshot_large.jpg), very specific case (e.g. README.md), and resolutions (though I can't remember what the recommended size was).

Perhaps we could align on a standard to recommend?

- JPG format
- At minimum: screenshot.jpg and screenshot_large.jpg, adding additional imagery as needed for the readme.
- screenshot.jpg should be 150 pixels for the largest dimension.
- screenshot_large.jpg should be at minimum 1000 pixels for the largest dimension, or at maximum up to 2000 pixels.

**Comment by DRx3D** [comment]
@echadwick-wayfair: Please review the draft of the `SubmittingModels` instructions at https://github.com/DrX3D/glTF-Sample-Assets/blob/main/SubmittingModels.md

It should address all of the above points; however, some of instructions are not yet supported.

**Comment by echadwick-artist** [comment]
Looks great, thanks Leonard.
